project:
  type: book

book:
  title: "Back Trajectories for Raven Camp 2024"
  author: "Von P. Walden"
  date: "9/13/2024"
  chapters:
    - index.qmd
    - background.qmd
    - creation.qmd
    - analysis.qmd
    - dashboard.qmd
    - references.qmd
  sidebar:
    tools:
      - icon: twitter
        menu:
          - text: WSU
            href: https://x.com/vpwalden      
      - icon: github
        menu:
          - text: GitHub Repo
            href: https://github.com/icecaps-summit/back-trajectories

bibliography: references.bib

format:
  html:
    theme: yeti
  pdf:
    documentclass: scrreprt



