# Trajectory Analysis {.unnumbered}

## Ideas for analysis

- **Diabatic vs adiabatic heating/cooling**

- **Moisture uptake**

This method comes from @sodemannInterannualVariabilityGreenland2008; they cite @jamesClimatologicalAspectsExtreme2004. One simply calculates the change in specific humidity between equally spaced periods along the trajectory.

- **Moisture Source Attribution**

This method comes from @sodemannInterannualVariabilityGreenland2008.

I think it might be interesting to plot symbols on the trajectory map that show moisture uptake (<font color="blue">blue</font> = evaporation) and moisture loss (<font color="red">blue</font> = precipitation; color represent gain and loss to the atmosphere). *Think about color choices here...*

- **Associate trajectory with cloud base height**

Determine the cloud-base height at each trajectory time. (This can be done using the CL61 summary files at 15 minute resolution.) Then select the vertical level that is closest to the cloud-base height. Plot all of these trajectories together to determine if they might be categorized. Determine the SOMs that are associated with the resulting categories; see below.

- **Associate trajectory with Self Organizing Map**

Determine the SOMs that are associated with each near-surface trajectory. I suspect that some SOMs will the associated with precipitation along the trajectory and some won't.

- **Regional trajectory analysis**

Use the methods of @hermannLagrangianAnalysisDynamical2020 to analyze multiple trajectories across the SW region of Greenland for the summer of 2024 to investigate how representative the SLEIGH measurements are. A lot of cool research questions here:

- How large of an area in SW Greenland if affected by similar conditions to Raven?
- How representative are the SLEIGH measurments under different atmospheric conditions (SOMs)?

## Ideas for plots

- Plot an individual trajectory in the context of ALL the trajectories at a given vertical level for the Raven 2024 field season. All the trajectories would use a very think line, while the desired trajectory would me bold and thick. Similar to Figure 2 in @hermannLagrangianAnalysisDynamical2020.

- Plot time series of an individual trajectory in the context of ALL the trajectories at a given vertical level for the Raven 2024 field season. Use shading to show the upper and lower quartiles and upper and lower deciles. Similar to Figures 2, 3, 5, 6, 7, 8 in @bieliLagrangianInvestigationHot2015.

- Create potential temperature (theta) vs air temperature (T) plots. Add lines of constant pressure. Similar to Figure 10 of @bieliLagrangianInvestigationHot2015 and Figure 10 of @hermannLagrangianAnalysisDynamical2020. (Note that Hermann plotted T vs theta instead of theta vs T).

  - $\theta$ vs. T
    - T changes while $\theta$ remains constant = adiabatic contribution
    - T and $\theta$ change in parallel = diabatic contribution

  - Trajectory time series showing median value and interquartile and interdecile ranges of: 
    - q
    - $\theta '$
    - lat - lat_0
    - p
    - T - To
    - $\theta - \theta_o$

