# Background {.unnumbered}

## Useful equations

### Potential temperture

$$
\theta = T \left( \frac{p_0}{p} \right)^{\kappa}
$$

where $\kappa = \frac{R_{air}}{c_p} = \frac{287 J kg^{-1} K^{-1}}{1005 J kg^{-1} K^{-1}} = 0.286$.

### Diabatic versus Adiabatic changes

$$
\frac{dT}{dt} = \frac{\kappa T \omega}{p} + H \left( \frac{p_o}{p} \right)^{-\kappa} = adiabatic + diabatic
$$

- the first term on the right represents the adiabatic heating/cooling from compression/expansion. $\omega$ > 0 for *descending* motion (compression and heating, + term).
- the second term on the right represents diabatic temperature changes from latent heating in clouds (rare at the surface), radiation, and surface fluxes. Therefore, the term H can be written as $H = H_{cld} + H_{rad} + H_{sfl}$.

### Changes in Moisture Content

$$
\frac{dq}{dt} \approx \frac{\Delta q}{\Delta t} = E - P = Evaporation - Precipitation \space [units: g \space kg^{-1} \space (1 h)^{-1}]
$$

- Thus, changes in the air parcel's moisture content can be approximated by simply determing the change in q (specific humidity) between each time step (because each time step is equal; 1 hour).

### Air Parcel Velocity

$$
\frac{d \textbf{x}}{dt} = \textbf{u(x)}
$$

## Back trajectory analysis

There are some excellent papers by Heini Wernli on the use of back trajectories to understand the history of air that arrives at a given location. In particular, these papers describe different ways that the air trajectories can be analyzed to understand:

- water vapor transport
- diabatic versus adiabatic heating/cooling

Here is a list of the important papers (in chronological order), including notes on how to use back trajectories for analysis:

---

### @sodemannInterannualVariabilityGreenland2008

#### A Lagrangian Moisture Source Diagnostic

##### Indentification of Moisture Uptake

- Assume air parcel "integrity"...
  - Identify where moisture enters an air parcel
  - Estimate which moisture sources contribute how much to precipitation at a specific location
- Only air parcels that are precipitating (RH > 80%) at t = 0 hours are analyzed
- 6 step method for determining location of moisture source regions
- This method allows for determining within-BL and above-BL uptake of moisture

##### Moisture Source Attribution

- Provides a method for determining what fraction of moisture uptake from a particular location contributes to precipitation from the air parcel. Thus, this provides information on the "relevance" of a particular source region for local precip.
  
#### Performance of the Method

##### Moisture Source NAO Variability

- This paper discusses how the moisture sources associated with precipitation on Greenland is affected by the NAO index; see Figure 6.
- Figure 8 shows the definition of "uptake sectors" in the Arctic and the fraction of contribution from each sector in different NAO regimes (+, neutral and -)

#### Evaluation of the Lagrangian Diagnositic

- Here the authors reconsider some of the assumptions, limitations and cavaets of this method of Lagrangian analysis.
- They also compare their new method to previous Lagrangian moisture source diagnostics.

---

### @bieliLagrangianInvestigationHot2015

#### Introduction

- This paper concentrates on the analysis of back trajectories during hot and cold extremes in Europe.
- 

---

### @hermannLagrangianAnalysisDynamical2020

#### Introduction

- Questions of the  study
  1. How often did large-scale melt events occur over the GrIS during 1979-2017?
  2. What are the synoptic flow configuration and the air mass pathways during these melt events?
  3. Which thermodynamic air mass modifications and radiative effects over the GrIS accumulation zone caused these melt events?
  4. Does the answer to Q2 and Q3 differ for subregions of the GrIS accumulation zone?

####

---

### @papritzMoistureOriginTransport2022


